// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api.DBContext;

namespace api.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20190922170119_AddColunaPrioridadeLista")]
    partial class AddColunaPrioridadeLista
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("api.Models.Lista", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DataCriacao");

                    b.Property<DateTime>("DataFinalizacao");

                    b.Property<DateTime>("DataUltimaAtualizacao");

                    b.Property<string>("Descricao");

                    b.Property<bool>("Finalizada");

                    b.Property<string>("Observacao");

                    b.Property<int>("Prioridade");

                    b.HasKey("ID");

                    b.ToTable("Listas");
                });

            modelBuilder.Entity("api.Models.TarefaLista", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DataCriacao");

                    b.Property<DateTime>("DataFinalizacao");

                    b.Property<DateTime>("DataUltimaAtualizacao");

                    b.Property<string>("Descricao");

                    b.Property<bool>("Finalizada");

                    b.Property<int?>("ListaID");

                    b.HasKey("ID");

                    b.HasIndex("ListaID");

                    b.ToTable("Tarefas");
                });

            modelBuilder.Entity("api.Models.TarefaLista", b =>
                {
                    b.HasOne("api.Models.Lista", "Lista")
                        .WithMany()
                        .HasForeignKey("ListaID");
                });
#pragma warning restore 612, 618
        }
    }
}
